# Generated by Django 5.0.3 on 2024-03-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='intro',
            new_name='subtitle',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='aurthor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
