# Generated by Django 5.0.3 on 2024-03-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_rename_intro_blogpost_subtitle_blogpost_aurthor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='aurthor',
            new_name='author',
        ),
    ]
